Algoritmo "exemplo 1 aula dia 13/4"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/13/2022
Var
// Seção de Declarações das variáveis 
   x: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Escreva o valor de X:")
   leia (x)
   escreval ("O valor da variável X é:", x)
   escreva ("O valor de X² é: ", x^2)

Fimalgoritmo